# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: config-map
#   namespace: expense
# data:
#   DB_HOST: mysql

# ---
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    project: for_deploy
    env: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      project: frontend
      env: frontend
  template:
    metadata:
      name: deployement
      labels:
        app: nginx
        project: frontend
        env: frontend
    spec:
      containers:
      - name: frontend
        image: munaga123/frontend:v1.0
        # envFrom:
        # - configMapRef:
        #     name: config-map
---

apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: expense
spec:
  selector:
    environment: "dev"
    connection:  "frontend"
  ports:
  - name: nginx
    protocol: TCP
    port: 80 #service port
    targetPort: 80 #target port

    