apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: expense
data:
  DB_HOST: mysql

---
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: for_deploy
    env: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      project: backend
      env: backend
  template:
    metadata:
      name: deployement
      labels:
        app: nginx
        project: backend
        env: backend
    spec:
      containers:
      - name: backend
        image: munaga123/backend:v1.0
        envFrom:
        - configMapRef:
            name: config-map
---

apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: expense
spec:
  selector:
    environment: "dev"
    connection:  "backend"
  ports:
  - name: nginx
    protocol: TCP
    port: 80 #service port
    targetPort: 80 #target port

    